### ISSUE TITLE
Instances of selecting facet wrap vs facet grid

### ISSUE THREAD

**Issue by varunjakki** [EmmaWoodONS/SDG_Data_Explorer_app#13]
Issue of which characteristic becomes the colour of the line and which becomes the faceting wrap characteristic

**Comment by varunjakki** [comment]
- Possible solution:  Add dropdown selections similar to Radiant App where there would be three dropdowns which would ask the user which disaggregation would be the line colour e.g. Sex and then the other selection(s) would automaticlaly become the Facet wrapping/Grid characteristic

**Comment by EmmaWoodONS** [comment]
At it's most basic, we could just have three dropdowns that are always available: line colour, facet rows, and facet columns, and the user can select anything from any of them.

**Comment by EmmaWoodONS** [comment]
Ideas relating to this issue are in the user_interface branch in user_interface_ideas
