### ISSUE TITLE
one function one action for plotting functions

### ISSUE THREAD

**Issue by EmmaWoodONS** [EmmaWoodONS/SDG_Data_Explorer_app#15]
At the moment there are two plotting functions with lines that are repeated. Putting repeated elements in their own functions so everything is only written once. e.g. have a basic_plot function that creates the axes and adds the points, another function that does the facets, another that does title etc. Pull them all together in the main code.

**Comment by varunjakki** [comment]
- https://stackoverflow.com/questions/56990018/adding-multiple-layers-to-a-ggplot-with-a-function -- Seems to be a similar issue with same error message, they have used list to combat this

- https://rdrr.io/cran/ggplot2/man/gg-add.html -- Example of using %+% to add to a GGplot - looked promising

**Comment by EmmaWoodONS** [comment]
@varunjakki @morrid9 Hi both, It occurred to me last night that I have become rather function obsessed, and while I still think the ggplot needs to be broken down into sections so that every user selection combination is accomodated, those sections don't actually need to be functions. Hopefully this will solve the issue you were having yesterday, and make everything more straightforward! Let me know if this doesn't make sense or you want to chat through it! Many apologies for making it harder than it needed to be!
