### ISSUE TITLE
Issue with trying to filter for lower level disaggregation (2/3 layers of disaggregation)

### ISSUE THREAD

**Issue by varunjakki** [EmmaWoodONS/SDG_Data_Explorer_app#23]
Currently the Shiny app requires the user to select all 4 dropdowns and the issue is that we do not know when the user will want to stop filtering hence the code does not know which stage filtering dataframe to use (filtering1, filtering2....). The solution is to ask the user how many layers of disaggreation they wish to filter for and then the code knows which dataframe to use. 

We would use an if statement to implement this and still looking into how to make this work as there are some reactivity issues.

**Comment by EmmaWoodONS** [comment]
used selectizeGroupUI function to get round issue
