### ISSUE TITLE
Select indicators with different requirements and plot

### ISSUE THREAD

**Issue by EmmaWoodONS** [EmmaWoodONS/SDG_Data_Explorer_app#9]
e.g. different number of options/ series/units buttons etc
1. Use ggplot to display each as required 
2. make this into a function so it works for all indicators

**Comment by varunjakki** [comment]
- 8.5.1 - series example (labelled as units of measurement - is this wrong?)
- 3.2.2 - units of measurement example

**Comment by EmmaWoodONS** [comment]
Series needs to be the first selection once someone has selected an indicator (if there are multiple series for the selected options)

**Comment by varunjakki** [comment]
- Made plots for series and units of measurement - can be found on sharepoint
- Function for facetting through ggplot - all can be found  as a branch
- Plots currently still have points plotted from other disaggregations - can be removed through filtering (create function for this)
- which blank cells are empty because they are headline figures for that column and which blank cells are empty for the use of other dissaggretions (steal function from control sheet - may be a solution to fill blank cells)

**Comment by EmmaWoodONS** [comment]
@morrid9 @varunjakki 

I have fixed the issue with the ggplot function. It won't quite work in the script with the current configs because it doesn't like that facet1 is NA. However, the following does work:

```
 test_facet_args <- function(df, facet2, linecolour) {
   
   facet2 <- sym(facet2)
   linecolour <- sym(linecolour)
  
   df <- df %>% 
     mutate(facet1 = !!(enquo(facet1)),
            facet2 = !!(enquo(facet2)),
            linecolour = !!(enquo(linecolour)))
   
   ggplot(data = df, 
          aes(Year, Value))+
     geom_line(aes(colour = !!linecolour)) +
     geom_point()+
     labs(title = "Percentage of Men in all regions of England of all age ranges who are current cigarette smokers aged 18 years and older",
          y = "Percentage(%)", x = "") +
     facet_grid(. ~ facet2)
   
 }
 
 test_facet_args(filtered_data,
                linecolour = line_colour, 
                facet2 = facet_row)
```

So I think the next step is to build in some if statements and maybe build the plot in sections so that it builds a different chart depending on what the user has selected (i.e. what is in the config file) e.g. something along the lines of the following (but with some if statements added in)
```
base_plot <- ggplot(data = df, 
          aes(Year, Value))

plot_with_lines <- base_plot +
          geom_line(aes(colour = !!linecolour)) 

plot_with_points <- base_plot +
          geom_point() 

# etc.
```
you'll probably need to create some variables to use in the if statements e.g. `facet_row_selected` , `linecolour_selected` etc

Let me know if this doesn't make sense

**Comment by varunjakki** [comment]
@EmmaWoodONS @morrid9 

12/05/2021 - Shiny session review

- Used above code by Emma to implemement when user has chosen to facet once - hence a facet_wrap with line colour being sex. This is now it's own function.

- We have built upon that code to make a function where both Facet1 and Facet2 are present.

- Both these functions have been put in a script named 'Plotting_functions', which is called from the main script using 'Source'.

- Implemented a if statement to see if either facet1 or facet2 are NA then use Emma's function for facet_wrapping, or else use new function for facet_grid. This has been tested and works, with the according plots being produced dependant on the user inputs in the config file.
